name: reversible-ode-gen-class
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision>=0.15
  - pytorch-cuda=12.1
  - pip
  - pip:
      - -r requirements.txt
      - -r requirements-eval.txt
